# frpc è¿æ¥frpsçš„é…ç½®
serverAddr = "æœåŠ¡å™¨IP"
serverPort = 7000
auth.token = "ä»¤ç‰Œ"

[[visitors]]
name = "p2p_ssh_visitor"
type = "xtcp"
serverName = "p2p_ssh"
secretKey = "abcdefg"
bindAddr = "127.0.0.1"
bindPort = 6000
# ä¸ºtrueæ—¶ï¼Œä¼šä¿æŒTCPéš§é“çš„è¿æ¥ï¼ˆğŸ¤”å¯èƒ½é€šè¿‡å‘ç©ºåŒ…ä¿æ´»ï¼‰ï¼Œå¦‚æœä¸ºfalseè¿‡ä¸€ä¼šå„¿å¯èƒ½ä¼šæ–­å¼€
keepTunnelOpen = true