services:
  mihomo:
    container_name: mihomo
    image: docker.io/metacubex/mihomo:Alpha
    restart: on-failure:10
    ports:
      - "9097:9097"
      - "7897:7897"
    volumes:
      - ./config.yaml:/root/.config/mihomo/config.yaml
  
  # 面板，可以直接用 https://metacubex.github.io/metacubexd （官方github静态站点）访问
  # metacubexd:
  #   container_name: metacubexd
  #   image: ghcr.io/metacubex/metacubexd
  #   restart: always
  #   ports:
  #     - '80:80'
  #   environment:
  #     # 设置mihomo内核api控制地址
  #     - DEFAULT_BACKEND_URL=http://192.168.1.1:9090